version: 2.1

# Executors definition
executors:
  sbt_executor:
    parameters:
      RUBY_VERSION:
        type: string
        default: 2.4.1
    docker:
      - image: circleci/ruby:<< parameters.RUBY_VERSION >>
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb


commands:
  compile_test:
    description: "Manage dependency cache with compile and test"
    steps:
      - run: |
          echo "Value of image_name is $image_name"
          echo "Value of regression_status is $regression_status"
          if [[ -z "$image_name" ]]; then
             echo "image_name is null, exiting"
             circleci-agent step halt
          else
             echo 'export regression_status=true' >> $BASH_ENV
             echo "BASH_ENV=$BASH_ENV"
             source $BASH_ENV
             echo "After export regression_status = $regression_status"
          fi
          

jobs:
  build_test_deploy:
    parameters:
      REG_CHECK:
        type: env_var_name
        default: regression_status
    environment:
      regression_status: false
      image_name: model-cmm
    executor: sbt_executor
    steps:
      - checkout
      - compile_test
      - run: echo "after next REG_CHECK = << parameters.REG_CHECK >>"
      - when:
          condition: << parameters.REG_CHECK >>
          steps:
            - setup_remote_docker



workflows:
  version: 2.1
  build:
    jobs:
      - build_test_deploy:
          filters:
            branches:
              only: master
