version: 2.1

# Executors definition
executors:
  sbt_executor:
    parameters:
      JDK_VERSION:
        type: string
        default: 11.0.2-jdk
    docker:
      - image: circleci/openjdk:<< parameters.JDK_VERSION >>
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb


commands:
  compile_test:
    description: "Manage dependency cache with compile and test"
    parameters:
      image_name:
        type: string
        default: ""
      regression_status:
        type: string
        default: "0"
    steps:
      - run: |
          echo "Value of image_name is << parameters.image_name >>"
          echo "Value of regression_status is << parameters.regression_status >>"
          if [[ -z "${<< parameters.image_name >>}" ]]; then
             echo "image_name is null, exiting"
             circleci-agent step halt
          else
             regression_status=1
          fi
          



jobs:
  build_test_deploy:
    parameters:
      regression_status:
        type: string
      image_name:
        type: string
    executor: sbt_executor
    steps:
      - checkout
      - compile_test
      - when:
          condition: 
             equals: ["<< parameters.regression_status >>", "1"]
          steps:
            - setup_remote_docker



workflows:
  version: 2.1
  build:
    jobs:
      - build_test_deploy:
          image_name: model-cmm
          regression_status: "2"
          filters:
            branches:
              only: master
