version: 2.1

# Executors definition
executors:
  sbt_executor:
    parameters:
      JDK_VERSION:
        type: string
        default: 11.0.2-jdk
    docker:
      - image: circleci/openjdk:<< parameters.JDK_VERSION >>
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb


commands:
  compile_test:
    description: "Manage dependency cache with compile and test"
    steps:
      - run: |
          echo "Value of image_name is $image_name"
          echo "Value of regression_status is $regression_status"
          if [[ -z "$image_name" ]]; then
             echo "image_name is null, exiting"
             circleci-agent step halt
          else
             export regression_status=1 >> $BASH_ENV
             source $BASH_ENV
             echo "After export regression_status = $regression_status"
          fi
          

  print_test:
    description: "printing the environmebt value"
    steps:
      - run: |
          source $BASH_ENV
          echo "Next command regression_status = $regression_status"


jobs:
  build_test_deploy:
    environment:
      regression_status: ""
      image_name: model-cmm
    executor: sbt_executor
    steps:
      - checkout
      - compile_test
      - print_test
      - when:
          condition: 
             equals: ["$regression_status", "1"]
          steps:
            - setup_remote_docker



workflows:
  version: 2.1
  build:
    jobs:
      - build_test_deploy:
          filters:
            branches:
              only: master
